<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/> 

    <xacro:property name="chassis_length" value="0.250"/>
    <xacro:property name="chassis_width" value="0.150"/>
    <xacro:property name="chassis_height" value="0.1"/>
    <xacro:property name="chassis_mass" value="1.85"/>
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_thickness" value="0.027"/>
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0"/>
    <xacro:property name="wheel_offset_y" value="0"/>
    <xacro:property name="wheel_offset_z" value="0.025"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.031"/>
    <xacro:property name="caster_wheel_offset_x" value="0.215"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- BASE LINK -->

    <link name="base_link">
        
    </link>
    <!-- Chassis link -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="${wheel_offset_x} 0 ${wheel_offset_z}"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <mesh filename="file://$(find my_bot)/meshes/chassis_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
          <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="chassis_link">
      <material>Gazebo/Orange</material>
    </gazebo>

<!-- Left wheel -->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="0.053 -0.09 ${wheel_offset_z+0.008}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>
    <link name="left_wheel_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find my_bot)/meshes/wheel_link.dae" />
            </geometry>
        </visual>   
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="left_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>

    <!-- Right wheel -->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="0.053 0.09 ${wheel_offset_z+0.008}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>
    <link name="right_wheel_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find my_bot)/meshes/wheel_link.dae" />
            </geometry>
        </visual>   
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="right_wheel_link">
      <material>Gazebo/Black</material>
    </gazebo>


<!-- caster_wheel_link -->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>
    <link name="caster_wheel_link">
        <visual>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find my_bot)/meshes/caster_wheel_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin
                xyz="0 0 0"
                rpy="0 0 0" />
            <geometry>
                <sphere radius="${caster_wheel_radius+0.02}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
    <gazebo reference="caster_wheel_link">
        <material>Gazebo/DarkGray</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

</robot>
    
    